name: Bump TOC

on:
  workflow_dispatch:
    inputs:
      interface_version:
        description: 'New interface version (e.g., 110107)'
        required: true
        type: string
      game_version:
        description: 'Game version description (e.g., 11.0.7)'
        required: false
        type: string

jobs:
  bump-toc:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate interface version
      run: |
        INTERFACE="${{ github.event.inputs.interface_version }}"
        if ! [[ $INTERFACE =~ ^[0-9]{5,6}$ ]]; then
          echo "ERROR: Invalid interface version format. Expected 5-6 digits (e.g., 110107)"
          exit 1
        fi
        echo "Interface version validation passed: $INTERFACE"
        
    - name: Update TOC file
      run: |
        INTERFACE="${{ github.event.inputs.interface_version }}"
        GAME_VERSION="${{ github.event.inputs.game_version }}"
        
        # Update interface version
        sed -i "s/^## Interface: .*/## Interface: $INTERFACE/" Crosspaths.toc
        
        # Verify the change
        if ! grep -q "^## Interface: $INTERFACE" Crosspaths.toc; then
          echo "ERROR: Failed to update interface version in Crosspaths.toc"
          exit 1
        fi
        
        echo "Successfully updated interface version to $INTERFACE"
        
        # Show the updated TOC file
        echo "Updated Crosspaths.toc:"
        head -10 Crosspaths.toc
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Bump interface version to ${{ github.event.inputs.interface_version }}"
        title: "Bump interface version to ${{ github.event.inputs.interface_version }}"
        body: |
          ## Interface Version Update
          
          This PR updates the WoW interface version to support the latest game version.
          
          **Changes:**
          - Interface version: `${{ github.event.inputs.interface_version }}`
          ${{ github.event.inputs.game_version && format('- Game version: `{0}`', github.event.inputs.game_version) || '' }}
          
          **Files modified:**
          - `Crosspaths.toc` - Updated `## Interface` field
          
          This change ensures compatibility with the latest World of Warcraft patch.
          
          Auto-generated by the Bump TOC workflow.
        branch: update-interface-${{ github.event.inputs.interface_version }}
        delete-branch: true