name: Bump TOC

on:
  workflow_dispatch:
    inputs:
      interface_version:
        description: 'New interface version (e.g., 110107)'
        required: true
        type: string
      game_version:
        description: 'Game version description (e.g., 11.0.7)'
        required: false
        type: string
      version_increment:
        description: 'Version increment type (none, patch, minor, major)'
        required: false
        default: 'none'
        type: choice
        options:
        - none
        - patch
        - minor
        - major

jobs:
  bump-toc:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate interface version
      run: |
        INTERFACE="${{ github.event.inputs.interface_version }}"
        if ! [[ $INTERFACE =~ ^[0-9]{5,6}$ ]]; then
          echo "ERROR: Invalid interface version format. Expected 5-6 digits (e.g., 110107)"
          exit 1
        fi
        echo "Interface version validation passed: $INTERFACE"
        
    - name: Validate version increment
      run: |
        INCREMENT="${{ github.event.inputs.version_increment }}"
        if [[ "$INCREMENT" != "none" && "$INCREMENT" != "patch" && "$INCREMENT" != "minor" && "$INCREMENT" != "major" ]]; then
          echo "ERROR: Invalid version increment type: $INCREMENT"
          exit 1
        fi
        echo "Version increment validation passed: $INCREMENT"
        
    - name: Bump semantic version
      if: github.event.inputs.version_increment != 'none'
      run: |
        chmod +x .github/scripts/bump-version.sh
        
        echo "Current version before bump:"
        grep "^## Version:" Crosspaths.toc
        grep "Crosspaths.version = " Core.lua
        
        ./.github/scripts/bump-version.sh "${{ github.event.inputs.version_increment }}"
        
        echo "Version after bump:"
        grep "^## Version:" Crosspaths.toc
        grep "Crosspaths.version = " Core.lua
        
    - name: Update TOC file
      run: |
        INTERFACE="${{ github.event.inputs.interface_version }}"
        GAME_VERSION="${{ github.event.inputs.game_version }}"
        
        # Update interface version
        sed -i "s/^## Interface: .*/## Interface: $INTERFACE/" Crosspaths.toc
        
        # Verify the change
        if ! grep -q "^## Interface: $INTERFACE" Crosspaths.toc; then
          echo "ERROR: Failed to update interface version in Crosspaths.toc"
          exit 1
        fi
        
        echo "Successfully updated interface version to $INTERFACE"
        
        # Show the updated TOC file
        echo "Updated Crosspaths.toc:"
        head -10 Crosspaths.toc
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: |
          ${{ github.event.inputs.version_increment != 'none' && format('Bump version ({0}) and interface to {1}', github.event.inputs.version_increment, github.event.inputs.interface_version) || format('Bump interface version to {0}', github.event.inputs.interface_version) }}
        title: |
          ${{ github.event.inputs.version_increment != 'none' && format('Bump version ({0}) and interface to {1}', github.event.inputs.version_increment, github.event.inputs.interface_version) || format('Bump interface version to {0}', github.event.inputs.interface_version) }}
        body: |
          ## Version and Interface Update
          
          This PR updates the addon for the latest game version.
          
          **Changes:**
          - Interface version: `${{ github.event.inputs.interface_version }}`
          ${{ github.event.inputs.game_version && format('- Game version: `{0}`', github.event.inputs.game_version) || '' }}
          ${{ github.event.inputs.version_increment != 'none' && format('- Semantic version: {0} increment', github.event.inputs.version_increment) || '' }}
          
          **Files modified:**
          - `Crosspaths.toc` - Updated `## Interface` field${{ github.event.inputs.version_increment != 'none' && ' and `## Version` field' || '' }}
          ${{ github.event.inputs.version_increment != 'none' && '- `Core.lua` - Updated `Crosspaths.version` field' || '' }}
          
          This change ensures compatibility with the latest World of Warcraft patch.
          
          Auto-generated by the Bump TOC workflow.
        branch: update-${{ github.event.inputs.version_increment != 'none' && 'version-and-' || '' }}interface-${{ github.event.inputs.interface_version }}
        delete-branch: true